### ISSUE TITLE
Flyer: 8 Seiter oder 6 Seiter?

### ISSUE THREAD

**Issue by grefel** [freifunk-tuebingen/flyer#1]
Es gibt den großen

https://wiki.freifunk.net/images/5/5e/FF_Flyer_8seiter_98x98mm_Flyeralarm.pdf

und den kleinen 

https://wiki.freifunk.net/Datei:Flyer_6_seiten_preview.png

Ich finde 6 Seiten sind schon Info genug.

**Comment by alfonx** [comment]
Ich finde den "großen" inhaltlich besser.

**Comment by grefel** [comment]
Idee 6 machen, Inhalte vom 8 übernehmen.

Die Punkte 
- Irrtümer ausräumen
- Warum Freifunk?

sind toll...
