### ISSUE TITLE
Bitte erste Version des 6er-Falt-Flyers durchsehen ...

### ISSUE THREAD

**Issue by grefel** [freifunk-tuebingen/flyer#2]
Habe ein Logo eingebaut und die erste Version des Flyers gemacht. Bitte Feedback:
- [ ]  Was soll noch anders werden?
- [ ] Wie ist die Kontaktadresse (Web/Mail)?

**Comment by alfonx** [comment]
BItte folgende Änderungen machen im Kontaktbereich:
1. Web: http://www.freifunk-tuebingen.de
2. Mail-Zeile entfernen (wir schreiben das auf der Homepage)
1. Auf der 1. Seite die URL Ändern auf www.freifunk-tuebingen.de
2. Einstiegsmodell ab ca. 40€ (statt 25€)

**Comment by erictapen** [comment]
So, der Flyer scheint ja jetzt druckbar zu sein ;)
Vielen Dank!
